### ISSUE TITLE
Override current tablature pop-up window doesn't work sometimes

### ISSUE THREAD

**Issue by Nobaiha** [xzippyzachx/softwareproject_group9#10]
ID# 10
Who Raised: Nobaiha Zaman Rayta
Title: Override current tablature pop-up window doesn't work sometimes
Version: master - 823856fc829043e4af28117cf8e8d9016b24e834
Platform: Windows 10
Reproduction: 1. Open the application
2. Input a text tab
3. Convert and save tab
Expected Outcome: After pressing yes on the current tablature pop-up window it closes the windows and overrides the tablature
Actual Outcome: After pressing yes, the tab does get overridden but the popup window doesn't close. 
Priority: low
Severity: low
Screenshots:
![image](https://user-images.githubusercontent.com/77299896/112246616-5c003f80-8c29-11eb-9a79-641f110da847.png)

**Comment by xzippyzachx** [comment]
I cant seem to reproduce this issue. I have a feeling there is an error being thrown. Could you add a screenshot or log file of any errors in the console.

**Comment by Nobaiha** [comment]
Hi this is what the console showing: 
![image](https://user-images.githubusercontent.com/77299896/112251552-de8cfd00-8c31-11eb-819e-69927a0b96b3.png)

**Comment by xzippyzachx** [comment]
The issue has now been fixed.
