### ISSUE TITLE
Small Bug in the ClearPopUp.java file

### ISSUE THREAD

**Issue by Nobaiha** [xzippyzachx/softwareproject_group9#11]
ID# 11
Who Raised: Nobaiha Zaman Rayta
Title: Small Bug in the ClearPopUp.java file
Version: master - 823856f
Platform: Windows 10
Description: I installed a plugin called SpotBugs and ran it with this project. I got 7 bugs in total in the code. One bug is in the ClearPopUP.java file. I am attaching screenshots of the description of the bug.
Expected Outcome: No bugs in code
Actual Outcome: Some existing bug in the code 
Priority: low
Severity: low
Screenshots:
![image](https://user-images.githubusercontent.com/77299896/112251226-3e36d880-8c31-11eb-9289-12a5d498cb3a.png)
![image](https://user-images.githubusercontent.com/77299896/112251253-4abb3100-8c31-11eb-81c4-cbb351c366a9.png)

**Comment by xzippyzachx** [comment]
The code still works as expected. I am closing his issue since this is just a suggestion that using a static variable in this instance may be bad practice.
