### ISSUE TITLE
Small Bug in SuccessPopUp.java (Same as #11)

### ISSUE THREAD

**Issue by Nobaiha** [xzippyzachx/softwareproject_group9#12]
ID# 12
Who Raised: Nobaiha Zaman Rayta
Title: Small Bug in the SuccessPopUp.java file
Version: master - 823856f
Platform: Windows 10
Description: I installed a plugin called SpotBugs and ran it with this project. I got 7 bugs in total in the code. One bug is in the SuccessPopUp.java file. I am attaching screenshots of the description of the bug.
Expected Outcome: No bugs in code
Actual Outcome: Some existing bug in the code
Priority: low
Severity: low
Screenshots:
![image](https://user-images.githubusercontent.com/77299896/112251890-70950580-8c32-11eb-88e8-c76bcd1f4990.png)
![image](https://user-images.githubusercontent.com/77299896/112251913-7e4a8b00-8c32-11eb-95de-f025e484271e.png)

**Comment by xzippyzachx** [comment]
This issue is duplicated by: https://github.com/xzippyzachx/softwareproject_group9/issues/11
