### ISSUE TITLE
Cannot Process Tab With Spaces in Between

### ISSUE THREAD

**Issue by dokdek** [xzippyzachx/softwareproject_group9#13]
**Title:**
Cannot process tabs that have spaces between each string

**Reported By:**
Patchanon Suepai

**Version:**
Commit: 823856f

**Platform:**
MacOS Catalina
Java 15
Eclipse 4.18

**Reproduction:**

- Using this tab

|-----------0-----|-0---------------|

|---------0---0---|-0---------------|

|-------1-------1-|-1---------------|

|-----2-----------|-2---------------|

|---2-------------|-2---------------|

|-0---------------|-0---------------|

- Pasting this tab into the text area
- Hit convert
- Nothing happens. No error message, or no success message.

**Expected:**

Either an error message pops up if its not supported, or it should process

**Actual:**

Nothing happens.

**Priority:**
Medium

**Severity:**
Medium

**Screenshots:**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112381014-76392c80-8cc0-11eb-87a8-07d29d861585.png">

This is the input, no window pops up after hitting convert.

**Comment by xzippyzachx** [comment]
Your Reproduction steps are not detailed enough. I see that you selected Bass as the instrument (is this the case?). Could you also take a screenshot of any errors in the console.

Also your title does not make much sense!
Thanks!

**Comment by dokdek** [comment]
I did not select bass as instrument, it auto switches to bass. After manually selecting guitar as instrument, same thing occurs, no error or window appears. Apologies, which part of reproduction is not detailed enough? I take the tab listed above, and simply paste into the text box area and attempt to hit convert. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112385283-cff02580-8cc5-11eb-987f-2878094bd7d7.png">


There is a nullpointer error, here

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112385479-0cbc1c80-8cc6-11eb-9b76-f2445bb8eaf2.png">


Let me know if you require any more detail! Thanks!

**Comment by xzippyzachx** [comment]
Thank you. I was wondering if it was automatically switching to bass. The console error will help us understand the issue now.

**Comment by xzippyzachx** [comment]
The user should not be putting spaces between the tablature lines like this. Spaces between text tablature sections usually means that they are continuing the tablature on the next line. 

This was still causing an error when converting and we have now fixed that issue.
