### ISSUE TITLE
Formatting error received when a linebreak precedes the first measure

### ISSUE THREAD

**Issue by dokdek** [xzippyzachx/softwareproject_group9#14]
**Title:**
Formatting error received when a linebreak precedes the first measure

**Reported By:**
Patchanon Suepai

**Version:**
Commit: 823856f

**Platform:**
MacOS Catalina
Java 15
Eclipse 4.18

**Reproduction:**

- Using this tab:

|-----------0-----|-0-----------------|
|---------0---0---|-0-----------------|
|-------1-------1-|-1-----------------|
|-----2-----------|-2-----------------|
|---2-------------|-2-----------------|
|-0---------------|-0-----------------|

- Put a line break above the first string.
- A wrong formatting error shows up at the bottom.

**Expected:**

The tab should be able to be processed.

**Actual:**

A formatting error occurs.

**Priority:**
Low

**Severity:**
Low

**Screenshots:**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112390731-201eb600-8ccd-11eb-95a5-21011ff560ba.png">

**Comments:**

Unsure if this is intended behaviour.

**Comment by xzippyzachx** [comment]
This issue has been fixed
