### ISSUE TITLE
Override Current Tablature Error Persists

### ISSUE THREAD

**Issue by dokdek** [xzippyzachx/softwareproject_group9#15]
**Title:**
Override Current Tablature Error Persists

**Reported By:**
Patchanon Suepai

**Version:**
Commit: 823856f

**Platform:**
MacOS Catalina
Java 15
Eclipse 4.18

**Reproduction:**

- Open "Example.txt" from the sample tabs provided
- Open "DrumExample.txt" from the sample tabs provided
- "Override Current Tablature" error pops up
- Click "Yes"
- Tab gets overridden
- Error does not disappear

**Expected:**

Error should disappear when hitting yes

**Actual:**

The tab does get overriden, but the error message still appears after hitting yes

**Priority:**
Low

**Severity:**
Low

**Screenshots:**

The original tab

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112395470-d508a100-8cd4-11eb-9ca7-bf1f8666f0fd.png">

The tab is replaced as seen, but the error doesnt go away.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112395451-c6ba8500-8cd4-11eb-9a48-14c0828cfff3.png">

**Comment by xzippyzachx** [comment]
Could you send a screenshot of the console errors if there are any. Thanks!

**Comment by dokdek** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/47761030/112496398-16dc2a80-8d5b-11eb-9fba-419e755b3c31.png">

**Comment by xzippyzachx** [comment]
This issue has been fixed.
