### ISSUE TITLE
Bug Report - User Manual Installations Instructions Not Working

### ISSUE THREAD

**Issue by Deys2000** [xzippyzachx/softwareproject_group9#16]
## Bug Report 1/3 - Syed Quadri - Group 15

Category | Detail |
-|-
ID | 16
Raised By | Syed Quadri - Group 15
Error Name |  Instructions do not work, Unable to run Gradle Build
Error Description |  I have made repeated attempts at following the User Manual to install the software. The process is not working and I do not end up with the same interface on my Computer. I have communicated this to @qurafa and @Yalzahed and we have debugged in a zoom call with my shared screen to no avail.
Steps to Reproduce | Follow the exact steps in the user manual:<br/>On the very Last step, the Gradle tasks window does now allow me to run the application. 
Expected Result | The application should run according to the user manual and the following options are available under the TAb2MXL folder ![image](https://user-images.githubusercontent.com/29327897/112398090-b6f16f80-8cd9-11eb-9e50-d6740cc8cc2c.png)
Actual Result | I have no option to run the Gradle application, it displays an error instead ![image](https://user-images.githubusercontent.com/29327897/112397926-6a0d9900-8cd9-11eb-8723-afbcbac8dbc0.png)
Machine/Version/Platform | Windows 10, Eclipse Gradle Build, Java SE 15
Priority | Low Priority (affects few users)
Severity | High Severity (fatal to operations)

**Comment by xzippyzachx** [comment]
This issue seems to only be for this individual. It can be re-opened if it continues to be an issue
