### ISSUE TITLE
Bass tablature fails to convert to MusicXML

### ISSUE THREAD

**Issue by ennorom** [xzippyzachx/softwareproject_group9#18]
ID#: 18

Who raised: Elijah Nnorom

Title: Bass tablature fails to convert to MusicXML

Version: Github commit 823856f in the master branch

Platform: Windows 10

Reproduction: In order to reproduce this error copy and paste this sample tablature:
G|------------------|------------------|------------------|-----------------|
D|------------------|------------------|------------------|-----------------|
A|-7-----7-10--7--5-|-3-------2--------|-7-----7-10--7--5-|-3--5--3-2---0---| 
E|------------------|------------------|------------------|-----------------|
To see what happens perform the following steps;
- Get bass tablature into the window via copy and paste OR drag and drop
- Click the convert button

Expected: This should have converted the bass tablature to a MusicXml file and request the directory where you would like to save the file.

Actual: There was no response from the system after the "Convert to MusicXML" button was clicked.

Priority: low

Severity: low

Screenshots:
![image](https://user-images.githubusercontent.com/45472071/112407217-13f62100-8cec-11eb-9c54-707a903debbc.png)
Figure 1: This shows the user interface with the bass tablature that triggers this bug.

**Comment by xzippyzachx** [comment]
This issue has been fixed
