### ISSUE TITLE
drag and drop not working

### ISSUE THREAD

**Issue by MesaGonzalez-Miguel-216138323** [xzippyzachx/softwareproject_group9#19]
### id:
19
### Who raised:
Miguel Mesa
### Title:
Drag and drop not functioning properly
### Platform:
Windows 10
### Reproduction:
Attempting to drag and drop a text file containing a drum tab does not properly display or translate the file in the program
### Expected:
The expectation was that the program would display the given tablature and then translate it.
### Actual:
The program did not seem to initially recognize that a file was dropped into the drag and drop. upon trying to highlight the empty area the given tablature appeared but it was still not able to be translated.
### Priority:
High
### Severity:
Medium
### Screenshots:
![image](https://user-images.githubusercontent.com/46364294/112413574-d21ea800-8cf6-11eb-8208-1091dc3ae43f.png)

**Comment by xzippyzachx** [comment]
This issue has now been fixed.
