### ISSUE TITLE
Bug Report - Tune not Recognized

### ISSUE THREAD

**Issue by Obuya** [xzippyzachx/softwareproject_group9#21]
#### Issue description

the program does not recognize a guitar tune when the tuning is the same capital letter. 

#### Steps to reproduce the issue

1. past the following tab [test.txt](https://github.com/xzippyzachx/softwareproject_group9/files/6201871/test.txt)
2. give it an arbitrary name and a time signature of 4/4.
2. then select convert To MusicXML. 

#### Expected result

- The program converts the tab and prompts me for a place to save the converted Tab. 

#### Actual result

- An error stating tune not recognized is displayed and the tab is not converted. 

![error1](https://user-images.githubusercontent.com/52579841/112415187-ca143780-8cf9-11eb-8f80-e894b5be07ab.jpg)

**Comment by xzippyzachx** [comment]
This issue has been fixed and is a duplicate of https://github.com/xzippyzachx/softwareproject_group9/issues/24
