### ISSUE TITLE
Tablatures with improper formatting are accepted

### ISSUE THREAD

**Issue by ennorom** [xzippyzachx/softwareproject_group9#22]
ID#: 22

Who raised: Elijah Nnorom

Title: Tablatures with improper formatting are accepted

Version: Github commit 823856f in the master branch

Platform: Windows 10

Reproduction: In order to reproduce this error copy and paste this sample tablature:
|-----------0-----|-0------------- -|
|---------0---0---|-0---------------|
|-------1-------1-|-1---------------|
|-----2-----------|-2---------------|
|---2-------------|-2---------------|
|-0---------------|-0---------------|
To see what happens perform the following steps;
-Get tablature into the window via copy and paste OR drag and drop
-Click the convert button

Expected: There are two options. The first, the conversion to MusicXML happens but a warning informs the user that the format is not correct could also be specific and indicate that an "-" might be missing. The second option is to generate an error which means the conversion doesn't happen until this formating error is fixed.

Actual: There was no warning/error from the system after the "Convert to MusicXML" button was clicked. The system ignores the missing "-" and treats the tablature as if "-" is not missing.

Priority: low

Severity: low

Screenshots:
![image](https://user-images.githubusercontent.com/45472071/112415255-eadc8d00-8cf9-11eb-9ee9-c8f0d680f06a.png)
Figure 1: This shows the tablature that causes this issue and the window proves that the conversion still happens because if there was an error it wouldn't have shown up.

**Comment by Yalzahed** [comment]
this is not a bug it's a feature, but will display a warning in future releases

**Comment by Yalzahed** [comment]
Resolved
