### ISSUE TITLE
Bug Report - not a tab output

### ISSUE THREAD

**Issue by Obuya** [xzippyzachx/softwareproject_group9#23]
#### Issue description

the program does not produce a tablature output. 

#### Steps to reproduce the issue

1. past the following tab [tab.txt](https://github.com/xzippyzachx/softwareproject_group9/files/6201912/tab.txt
2. give it an arbitrary name and a time signature of 4/4.
3. then select convert To MusicXML. 
4. open and view the XML document in muse score. 

#### Expected result

![expected](https://user-images.githubusercontent.com/52579841/112415821-f11f3900-8cfa-11eb-8c9c-8ac253cf7538.jpg)

#### Actual result 
![error3](https://user-images.githubusercontent.com/52579841/112415861-fc726480-8cfa-11eb-988f-0079788cf605.jpg)

**Comment by xzippyzachx** [comment]
This issue has been fixed. The output now displays both tablature and regular sheet music.
