### ISSUE TITLE
Tune not recognized issue

### ISSUE THREAD

**Issue by suhasid098** [xzippyzachx/softwareproject_group9#24]
Title:
Tune not recognized issue
Author:
Suha Siddiqui

Version:
Commit: 823856f

Platform:
Windows 10
Java 15
Version: 2020-12 (4.18.0)

Reproduction:

Based on the user manual the following tab was entered into the content window:

e|-----------------|-----------------|
B|---3---3---4---2-|---3---3---4---2-|
G|-----------0---2-|-----------0---2-|
D|---3---3-------2-|---3---3-------2-|
A|-----1-------0---|-----1-------0---|
D|-0-------1-------|-0-------1-------|

Then the convert button was pressed to save the file in the file directory on my computer.

Expected:
The program should be able to process the tuning given in the input window.

Actual:

The program doesn't allow for conversion for the given tab when the "convert" button is pressed and indicated that the "Tune Not Recognized"

image
![image](https://user-images.githubusercontent.com/77293073/112416237-a94ce180-8cfb-11eb-94cb-113da696cf86.png)

Priority:
High

Severity:
High

**Comment by xzippyzachx** [comment]
This issue has been fixed
