### ISSUE TITLE
Repeat not indicated in final output

### ISSUE THREAD

**Issue by suhasid098** [xzippyzachx/softwareproject_group9#25]
Title:
Repeat not indicated in final output
Author:
Suha Siddiqui

Version:
Commit: 823856f

Platform:
Windows 10
Java 15
Version: 2020-12 (4.18.0)

Reproduction:

Based on the user manual the following tab was entered into the content window:

|-----------0-----||----------0--------4|
|---------0---0---||----------0--------||
|-------1-------1-||\*---------1-------\*||
|-----2-----------||\*---------2-------\*||
|---2-------------||------2---2--------||
|-0---------------||--0-------0--------||

Then the convert button was pressed to save the file in the file directory on my computer.

Expected:
The program should be able to process the repeat and display it in the final output.

Actual:

The output doesn't display the repeat.
![image](https://user-images.githubusercontent.com/77293073/112416599-5de70300-8cfc-11eb-8497-8b66a266d18b.png)

![image](https://user-images.githubusercontent.com/77293073/112416655-75be8700-8cfc-11eb-9104-51f554cacbe9.png)

Priority:
medium

Severity:
low

**Comment by xzippyzachx** [comment]
Repeated measures are not yet supported in this version. They are not listed as a feature in our user manual.
Closing this issue since this feature isn't actually added yet.
