### ISSUE TITLE
Bug Report - User interface

### ISSUE THREAD

**Issue by Obuya** [xzippyzachx/softwareproject_group9#26]
#### Issue description

The tab editor losses the ability to undo changes by means of "ctrl + z" after a save prompt of "convert To MusicXML" is displayed. 

#### Steps to reproduce the issue

1. supply the program with a valid tab. 
2. modify the tab on the editor i.e change a tuning 
3. then select convert To MusicXML. 
4. cancel the save.  

#### Expected result

- The tab editor allows me to redo/undo changes with common keyboard shortcuts. 

#### Actual result

- all history of changes is lost, the tab editor cannot revert back.

**Comment by ErikaGrandy** [comment]
Bug fixed - Undo and Redo now keeps all history, even after an attempted save
