### ISSUE TITLE
GUI Bug: Tab is invisible in text window.

### ISSUE THREAD

**Issue by Martin-Brejniak** [xzippyzachx/softwareproject_group9#7]
**ID:** 7

**Author:** Martin Brejniak.
**Contact Info:** martin.brejniak@bell.net

**Version:** March, 17/2021 Version of Software.
**Platform:** Windows 10. Eclipse 4.18.0. JavaSE-13.

**Reproduction:** I copied and pasted [this tab](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/drumexample.txt) into the text area. I then tried the other two methods of inputting a tab (The open button and dragging the file in).
**Expected:** I expected the text to show up right away, so I could look it over before converting.
**Actual:** Nothing appeared in the text box for a few seconds after pasting. Then the only the first character of my tab showed up. I assumed at first I didn't copy it correctly. However, upon highlighting the text did it become visible. The same thing happened when I tried the other two uploading methods.

**Priority:** Low.
**Severity:** Someone with less experience in using computers might not figure out that you need to highlight the text to make it appear, and might think that your software doesn't work. It greatly affects user-friendliness and should be dealt with before your final release.

_The text window as soon as I pasted the tab._
<img width="636" alt="Capture" src="https://user-images.githubusercontent.com/77299294/112081771-9fd84380-8b5a-11eb-994d-943759fa79bd.PNG">
_Highlighting a bit of the tab._
<img width="645" alt="Capture 2" src="https://user-images.githubusercontent.com/77299294/112081790-a36bca80-8b5a-11eb-8b82-260acebddc7c.PNG">
_Highlighting all the tab._
<img width="658" alt="Capture 3" src="https://user-images.githubusercontent.com/77299294/112081797-a5358e00-8b5a-11eb-8235-1206a8ed624c.PNG">
_After highlighting the tab, it is now visible._
<img width="649" alt="Capture 4" src="https://user-images.githubusercontent.com/77299294/112081806-a797e800-8b5a-11eb-9b24-1a6fc89b5d4e.PNG">

**Comment by xzippyzachx** [comment]
After investigating this issue I have concluded that this is happening because we hid the drum option in the instrument dropdown for this test submission (Because we don't have drum parsing yet). This was not an an issue anymore when I re-added the drum option to the dropdown.

This issue has been fixed for next update and I am closing this issue.
