### ISSUE TITLE
Guitar MusicXML Creation Bug: <divisions> and <duration> values in MusicXML file created by software are incorrect.

### ISSUE THREAD

**Issue by Martin-Brejniak** [xzippyzachx/softwareproject_group9#8]
**ID:** 8

**Author:** Martin Brejniak.
**Contact Info:** martin.brejniak@bell.net

**Version:** March, 17/2021 Version of Software.
**Platform:** Windows 10. Eclipse 4.18.0. JavaSE-13.

**Reproduction:** I copied and pasted [this tab](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/exampleemajor.txt) is the text area. I then converted it with the name, "~~~hhgfhgfhgfhgfsdfsd" with the default time signature (I didn't type anything into the time signature box).
**Expected:** I expected the MusicXML file to be almost identical to [this](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/exampleemajor.musicxml.txt).
**Actual:** Instead of `<divisions>2</divisions>`,  the MusicXML file had `<divisions>4</divisions>`. Instead of `<duration>1</duration>` & `<duration>8</duration>`, the MusicXML file had `<duration>2</duration>` & `<duration>16</duration>`.

**Priority:** High.
**Severity:** These two parts (Especially the `<duration>`) are important to parts of the MusicXML file, and should be converted correctly. It seems as if the values are being doubled, and should not be that way by default. Take a look into these, and use the example I gave as a reference.

**The example is on the left. The created MusicXML file is on the right.**
<img width="887" alt="Capture" src="https://user-images.githubusercontent.com/77299294/112084979-11ff5700-8b60-11eb-8aac-a5f7e8917407.PNG">
<img width="920" alt="Capture 2" src="https://user-images.githubusercontent.com/77299294/112084986-1592de00-8b60-11eb-81a6-0c5688a649b0.PNG">

**Comment by qurafa** [comment]
Hi Martin, the **durations** and the **divisions** don't have to be exactly the same as the example you gave, as long as the ratio of the **duration** to **division** is the same as the ratio of the **note-type** to the **note** specified by the **beat-type**.
For example, the **note** denoted by the **beat-type** is a **quarter-note** i.e. **1/4** and the, the ratio of that to an **eight-note** is 2:1.
The **divisions** of the generated tablature is **4** and the **duration** of an **eight-note** is **2**, so the ratio is 2:1.
The same logic can be used for the example you provided, but the **division** is 2 and the **duration** is 1, but the ratio is still the same
