### ISSUE TITLE
GUI Bug: Instrument panel not displaying correct instrument.

### ISSUE THREAD

**Issue by Martin-Brejniak** [xzippyzachx/softwareproject_group9#9]
**ID:** 9

**Author:** Martin Brejniak.
**Contact Info:** martin.brejniak@bell.net

**Version:** March, 17/2021 Version of Software.
**Platform:** Windows 10. Eclipse 4.18.0. JavaSE-13.

**Reproduction:** I pasted [this tab](https://wiki.eecs.yorku.ca/course_archive/2020-21/W/2311/_media/exampleemajor.txt) into the text area. I gave it the title, "Bass" with the default time signature (I didn't type anything into the time signature box). After it was in, I changed the instrument from guitar to bass. I then converted the tab.
**Expected:** Since the instrument panel didn't automatically change to guitar, I expected either to get an error saying it doesn't recognize the tab as a bass tab or for it to tell me that it automatically switched the instrument to guitar.
**Actual:** After converting, the instrument panel didn't change, giving me the impression I just converted a guitar tab using the bass tab converting system. However, it automatically switched to the guitar tab converting system without notifying me.

**Priority:** Low.
**Severity:** Nothing should automatically change without letting the user know. It could give them a result they weren't looking for, and make them think your software isn't working. It affects user-friendliness and should be dealt with before your final release.

_Guitar tab, with instrument set to Bass._
<img width="930" alt="Capture" src="https://user-images.githubusercontent.com/77299294/112087254-fc8c2c00-8b63-11eb-93c0-62227fac780e.PNG">
_Saving the tab._
<img width="824" alt="Capture 2" src="https://user-images.githubusercontent.com/77299294/112087259-ff871c80-8b63-11eb-9e5b-7f78e7f559b6.PNG">
_The software telling me the convertion was successful._
<img width="651" alt="Capture 4" src="https://user-images.githubusercontent.com/77299294/112087798-04989b80-8b65-11eb-8980-3740f8b6076f.PNG">
_Instrument was set to guitar without telling me._
<img width="818" alt="Capture 3" src="https://user-images.githubusercontent.com/77299294/112087263-01e97680-8b64-11eb-919f-914bef8b5ff4.PNG">

**Comment by xzippyzachx** [comment]
I have now fixed this issue. The part-name is now set to the proper instrument name when generating the musicxml.
